name: Ping Render Server

on:
  schedule:
    # Har 14 daqiqada Render'ni uyg'otib turadi
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping to Render and hold
        run: |
          curl -s https://payment-managebot.onrender.com || echo "Ping yuborildi"
          sleep 40
